"""booking update

Revision ID: 9eb33247dc56
Revises: 754a9882a739
Create Date: 2026-03-22 18:33:53.708053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb33247dc56'
down_revision: Union[str, Sequence[str], None] = '754a9882a739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'phone')
    op.drop_column('bookings', 'name')
    # ### end Alembic commands ###
